export const ZOOM = {
  MIN: 50,
  MAX: 500,
  DEFAULT: 100,
  PDF_POINT_TO_CSS_PX: 96 / 72,
  MAX_PDFTOHTML_SCALE: 3.0,
} as const;

export const TABLE_DETECTION = {
  LINE_CLUSTER_TOLERANCE: 10,
  MIN_LINE_LENGTH: 5,
  CELL_MERGE_THRESHOLD: 15,
  HORIZONTAL_LINE_GAP_THRESHOLD: 15,
} as const;

export const VECTOR = {
  MIN_LINE_LENGTH: 5,
  THICK_LINE_FACTOR: 1.5,
  MAX_BORDER_RADIUS: 20.0,
  CORNER_CURVE_COUNT: 4,
} as const;

export const FONT = {
  WEIGHT_BLACK: 900,
  WEIGHT_EXTRABOLD: 800,
  WEIGHT_BOLD: 700,
  WEIGHT_SEMIBOLD: 600,
  WEIGHT_MEDIUM: 500,
  WEIGHT_REGULAR: 400,
  WEIGHT_LIGHT: 300,
  WEIGHT_EXTRALIGHT: 200,
  WEIGHT_THIN: 100,
  DEFAULT_WEIGHT: 400,
} as const;

export const CACHE = {
  MAX_ENTRIES: 256,
  HASH_LENGTH: 16,
} as const;
